default_platform(:android)
fastlane_require "dotenv"

platform :android do
  before_all do
    Dotenv.overload "../../.env"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  private_lane :increment_version do |options|
    env = options[:flavor]
    app = ENV['FB_DIS_PROD_APP_ID']
    latest_release = firebase_app_distribution_get_latest_release(
      app: app
    )
    android_set_version_code(
      version_code: latest_release ? latest_release[:buildVersion].to_i + 1 : 1,
      gradle_file: "app/build.gradle"
    )
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  private_lane :firebase_distribute do |options|
    env = options[:flavor]
    app = ENV['FB_DIS_PROD_APP_ID']
    firebase_app_distribution(
        app: app,
        groups: "InbeeTesters",
        firebase_cli_token: ENV['FIREBASE_TOKEN'],
        release_notes: "Lots of new avatars to try out!",
        android_artifact_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
    )
  end

  desc "Upload"
  lane :beta do |options|
    if options[:version]
      android_set_version_name(
        version_name: "#{options[:version]}",
        gradle_file: "app/build.gradle"
      )
      increment_version flavor:options[:flavor]
    else
      increment_version flavor:options[:flavor]
    end
    gradle(task: 'clean assemble', build_type: 'Release', flavor: options[:flavor].capitalize())
    firebase_distribute flavor:options[:flavor]
  end
end
